#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (C) 2022 Ing
#


name: Build OpenWrt

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: build
      run: |
        git clone https://github.com/destan19/openfros.git 
        
        cd openfros
        
        mkdir -p package/luci-app-openclash
        cd package/luci-app-openclash
        git init
        git remote add -f origin https://github.com/vernesong/OpenClash.git
        git config core.sparsecheckout true
        echo "luci-app-openclash" >> .git/info/sparse-checkout
        git pull --depth 1 origin master
        git branch --set-upstream-to=origin/master master
        
        product=r2s
        sed -i '/CONFIG_PACKAGE_luci-app-openclash/d' product/${product}/product_config
	      echo "CONFIG_PACKAGE_luci-app-openclash=y" >> product/${product}/product_config

        ./build.sh -l r2s
        
      
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: r2s
        path: |
          openfros/release/*
        
