#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (C) 2022 Ing
#


name: R2S

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: build
      run: |
        sudo apt update
        sudo apt install texlive
        
        git clone https://github.com/destan19/openfros.git 
        
        cd openfros
        
        mkdir -p package/openwrt-passwall
        (
        cd package/openwrt-passwall
        git init
        src-git passwall https://github.com/xiaorouji/openwrt-passwall
        git config core.sparsecheckout true
        echo "openwrt-passwall" >> .git/info/sparse-checkout
        git pull --depth 1 origin master
        git branch --set-upstream-to=origin/master master
        
        pushd openwrt-passwall/tools/po2lmo
        make && sudo make install
        popd
        )
        
        product=r2s
        sed -i '/CONFIG_PACKAGE_luci-app-passwall/d' product/${product}/product_config
        echo "CONFIG_PACKAGE_luci-app-passwall=y" >> product/${product}/product_config

        ./build.sh -l r2s
        
      
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: r2s
        path: |
          openfros/release/*
        
